[project]
dynamic = ["version"]

[build-system]
requires = [
    "conan>=2.0.0",
    "setuptools",
    "scikit-build>=0.17.3",
    "skbuild-conan",
    "cmake>=3.23",
    "ninja",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
include = "src/.*.pyi?$"
extend-exclude = '''
    src/ifcopenshell-python/ifcopenshell/express/*
    |src/ifcopenshell-python/ifcopenshell/mvd/*
    |src/ifcopenshell-python/ifcopenshell/simple_spf/*
    |src/ifc2ca/templates/*
    |src/ifcconvert/cityjson/*
    |src/svgfill
    |src/exterior-shell-extractor
    |src/pyodide
'''

[tool.pyright]
reportInvalidTypeForm = false
disableBytesTypePromotions = true
reportUnnecessaryTypeIgnoreComment = true

[tool.cibuildwheel]
before-all = "uname -a"
